/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JFrame;
import model.ServiceBank;
import model.User;
import model.Users;

/**
 *
 * @author xande
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * @param bank
     * @param serviceBank
     */
    public Login(Users bank, ServiceBank serviceBank) {
        initComponents();
        this.bank = bank;
        this.serviceBank = serviceBank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixaNome = new javax.swing.JTextField();
        buttonEntrar = new javax.swing.JButton();
        buttonCadastrar = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        textNome = new javax.swing.JLabel();
        textSenha = new javax.swing.JLabel();
        caixaSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        caixaNome.setBackground(new java.awt.Color(204, 255, 255));
        caixaNome.setToolTipText("nome");
        caixaNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caixaNomeFocusGained(evt);
            }
        });
        caixaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaNomeActionPerformed(evt);
            }
        });

        buttonEntrar.setBackground(new java.awt.Color(51, 255, 255));
        buttonEntrar.setText("Entrar");
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });

        buttonCadastrar.setBackground(new java.awt.Color(51, 255, 255));
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logo1.png"))); // NOI18N
        Logo.setText("jLabel1");

        textNome.setText("Nome:");

        textSenha.setText("Senha:");

        caixaSenha.setBackground(new java.awt.Color(204, 255, 255));
        caixaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNome)
                    .addComponent(caixaNome)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSenha)
                    .addComponent(caixaSenha)
                    .addComponent(buttonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(textNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(textSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caixaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(buttonEntrar)
                .addGap(18, 18, 18)
                .addComponent(buttonCadastrar)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        Cadastrar form = new Cadastrar(this.bank);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void caixaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaNomeActionPerformed

    private void caixaNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaNomeFocusGained

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarActionPerformed
        User aux = this.bank.login(this.caixaNome.getText(), String.copyValueOf(this.caixaSenha.getPassword()));
        if(aux == null){
            this.textNome.setText("Nome: (Login Inválido)");
            this.buttonEntrar.setBackground(Color.RED);
        }else{
            this.textNome.setText("Nome:");
            this.buttonEntrar.setBackground(Color.GREEN);
            this.page = new MainMenu(this.serviceBank, aux);
            page.setLocationRelativeTo(null);
            page.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            page.setVisible(true);
        }
    }//GEN-LAST:event_buttonEntrarActionPerformed

    private void caixaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaSenhaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JTextField caixaNome;
    private javax.swing.JPasswordField caixaSenha;
    private javax.swing.JLabel textNome;
    private javax.swing.JLabel textSenha;
    // End of variables declaration//GEN-END:variables
    private Users bank;
    private ServiceBank serviceBank;
    private JFrame page;
}


