/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ListModel;
import model.*;

/**
 *
 * @author xande
 */
public class MainMenu extends javax.swing.JFrame {

    private ServiceBank serviceBank;
    private String[] services;
    private ListModel<String> lista;
    private Service[] servicesArray;
    
    
    /**
     * Creates new form MainMenu
     * @param serviceBank
     * @param me
     */
    public MainMenu(ServiceBank serviceBank, User me) {
        this.serviceBank = serviceBank;
        services = getTitles();
        servicesArray = serviceBank.returnServices();
        
        lista = new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return services.length;
            }

            @Override
            public String getElementAt(int index) {
                return services[index];
            }

        };
        
        initComponents();
        
        if(me.getRank() < 2){
        this.btEdit.setVisible(false);
        }
    }
    
    public String[] getTitles(){
        Service[] serviceArray = serviceBank.returnServices();
        String[] names = new String[serviceArray.length];
        
        for(int i=0 ; i < serviceArray.length; i++){
            names[i] = serviceArray[i].getTitle();
        }
        
        return names;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJobs = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelDesc = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        btContratar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableJobs.setBackground(new java.awt.Color(204, 255, 255));
        tableJobs.setModel(this.lista);
        tableJobs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableJobs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tableJobsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tableJobs);

        labelTitle.setText("Title");

        labelDesc.setText("Desciption");
        labelDesc.setToolTipText("");
        labelDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btEdit.setText("Editar");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btContratar.setText("Fazer Proposta");
        btContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContratarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btEdit)
                        .addGap(56, 56, 56)
                        .addComponent(btContratar))
                    .addComponent(labelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(labelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdit)
                    .addComponent(btContratar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        EditMenu edit = new EditMenu(servicesArray[this.tableJobs.getSelectedIndex()], serviceBank);
        
        edit.setVisible(true);
    }//GEN-LAST:event_btEditActionPerformed

    private void tableJobsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tableJobsValueChanged
        this.labelTitle.setText(this.services[tableJobs.getSelectedIndex()]);
        this.labelDesc.setText(String.format("<html><div WIDTH=%d>%s</div></html>", 350, this.servicesArray[tableJobs.getSelectedIndex()].getDescription()));
    }//GEN-LAST:event_tableJobsValueChanged

    private void btContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContratarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btContratarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContratar;
    private javax.swing.JButton btEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JList<String> tableJobs;
    // End of variables declaration//GEN-END:variables
}
